title: Hapag-Lloyd Hackerschool
description: Aufgabensammlung für die Hapag-Lloyd Hackerschool 2025
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  "Hapag-Lloyd": https://www.hapag-lloyd.com

nav_external_links:
  - title: Color Picker
    url: https://www.w3schools.com/colors/colors_picker.asp
    opens_in_new_tab: true

collections:
  tasks:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    tasks:
      name: Aufgaben