title: Hapag-Lloyd Hackerschool
description: Aufgabensammlung für die Hapag-Lloyd Hackerschool 2025
theme: just-the-docs

url: https://just-the-docs.github.io

color_scheme: hl

nav_external_links:
  - title: Color Picker
    url: https://www.w3schools.com/colors/colors_picker.asp
    opens_in_new_tab: true
  - title: CSS Reference
    url: https://cssreference.io/
    opens_in_new_tab: true

collections:
  tasks:
    output: true
    permalink: /:path/
  next_steps:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    tasks:
      name: Aufgaben
    next_steps:
      name: Nächste Schritte

enable_copy_code_button: false
back_to_top: true
back_to_top_text: "zum Seitenanfang"

callouts:
  warning:
    title: Warnung
    color: red
  highlight:
    color: yellow
  important:
    title: Wichtig
    color: blue
  new:
    title: Neu
    color: green
  note:
    title: Aufgabe
    color: purple
  task:
    title: Aufgabe
    color: yellow
  extra-task:
    title: Zusatzaufgabe
    color: purple